[package]
name = "rgb_utils"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
directories = "6.0.0"
hex = "0.4.3"
once_cell = "1.21.3"
rusb = "0.9"
serde_json = "1.0.140"
tokio = "1.45.1"
udev = "0.9.3"
